# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/halol/halol.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==halol || ORIG_REF_NAME==halol} -quiet] -quiet

# IP: bd/halol/ip/halol_processing_system7_0_0/halol_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==halol_processing_system7_0_0 || ORIG_REF_NAME==halol_processing_system7_0_0} -quiet] -quiet

# IP: bd/halol/ip/halol_axi_gpio_0_0/halol_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==halol_axi_gpio_0_0 || ORIG_REF_NAME==halol_axi_gpio_0_0} -quiet] -quiet

# IP: bd/halol/ip/halol_axi_gpio_1_0/halol_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==halol_axi_gpio_1_0 || ORIG_REF_NAME==halol_axi_gpio_1_0} -quiet] -quiet

# IP: bd/halol/ip/halol_xbar_0/halol_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==halol_xbar_0 || ORIG_REF_NAME==halol_xbar_0} -quiet] -quiet

# IP: bd/halol/ip/halol_ps7_0_axi_periph_0/halol_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==halol_ps7_0_axi_periph_0 || ORIG_REF_NAME==halol_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/halol/ip/halol_rst_ps7_0_50M_0/halol_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==halol_rst_ps7_0_50M_0 || ORIG_REF_NAME==halol_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/halol/ip/halol_auto_pc_0/halol_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==halol_auto_pc_0 || ORIG_REF_NAME==halol_auto_pc_0} -quiet] -quiet

# XDC: bd/halol/halol_ooc.xdc
